name: unibg_pokemon
description: "Source code of the demo Pokédex app made for my lecture at UniBG"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  audioplayers: ^6.4.0
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+6
  pinch_zoom: ^2.0.1
  universal_platform: ^1.1.0
  window_manager: ^0.4.3
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
